// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8v9OkERZ9rWiiNHS1U-8qze1RaDQMdY',
    appId: '1:897078125338:web:7b7537485f51b100c042a3',
    messagingSenderId: '897078125338',
    projectId: 'yummify',
    authDomain: 'yummify-18fc3.firebaseapp.com',
    storageBucket: 'yummify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCzdXlfHWYP3T4VzOUrzdRWFLuqkaJN4',
    appId: '1:897078125338:android:eab8fdc65f78c1a4c042a3',
    messagingSenderId: '897078125338',
    projectId: 'yummify',
    storageBucket: 'yummify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_wlkjqJtdjl2OpKIyJllgd3jud7tZUJk',
    appId: '1:897078125338:ios:ea58b47c3367b365c042a3',
    messagingSenderId: '897078125338',
    projectId: 'yummify',
    storageBucket: 'yummify.appspot.com',
    iosClientId: '897078125338-71rdcpdr9kih8lufdlhlk6jf1casbm89.apps.googleusercontent.com',
    iosBundleId: 'tm.com.yummify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_wlkjqJtdjl2OpKIyJllgd3jud7tZUJk',
    appId: '1:897078125338:ios:ea58b47c3367b365c042a3',
    messagingSenderId: '897078125338',
    projectId: 'yummify',
    storageBucket: 'yummify.appspot.com',
    iosClientId: '897078125338-71rdcpdr9kih8lufdlhlk6jf1casbm89.apps.googleusercontent.com',
    iosBundleId: 'tm.com.yummify',
  );
}
